# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 00034a6626fc21dd3fd354aa8e202186c467b4482d9fbef146558f5d54dea8c2f18ca6fba190cd7632f75c320e637a8b941e7416f431f4be38abbc2c40309f0e

test:
  secret_key_base: 1b5c1babcdca6d915b018c21ea50a8fa85790b0e0b3e00a96e4c517b81ab040f74e76aec86c8d924f1954988dcb7b56bf10a60118b751916fdf44bfcf81b09bf

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
